In [1]:
import numpy as np
import random

In [5]:
#Creación y Indexación:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array = np.random.randint(10, 100, (50))
array

array([42, 27, 77, 72, 25, 43, 27, 90, 33, 89, 55, 48, 65, 72, 78, 60, 40,
       74, 19, 35, 97, 27, 94, 32, 17, 69, 25, 21, 30, 43, 79, 50, 71, 47,
       73, 96, 32, 54, 39, 53, 47, 63, 83, 20, 40, 87, 17, 16, 70, 94])

In [6]:
array[::5]

array([42, 43, 55, 60, 97, 69, 79, 96, 47, 87])

In [7]:
#Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

array1 = np.random.randint(1, 21, (30))
array1

array([12,  4,  2, 13,  3, 15, 12,  9,  5,  7, 17,  5, 15,  2, 16, 17,  4,
       15,  2,  4, 18,  2,  3,  1, 10,  4, 10, 11,  7, 13])

In [8]:
array1[::2]

array([12,  2,  3, 12,  5, 17, 15, 16,  4,  2, 18,  3, 10, 10,  7])

In [9]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
#Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array2D = np.random.rand(4, 6) * 30
array2D_round = np.round(array2D,2)
array2D_round

array([[18.36, 18.41,  9.88, 13.17, 16.8 , 17.62],
       [ 6.86, 12.49, 18.94,  7.76, 28.09, 11.53],
       [28.27, 22.11, 29.21,  7.7 , 24.73,  2.05],
       [25.64,  0.13, 12.12,  9.39, 16.75, 25.02]])

In [10]:
array2D_round[-1]

array([25.64,  0.13, 12.12,  9.39, 16.75, 25.02])

In [11]:
#Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

array4 = np.random.rand(6, 4)
array4_round = np.round(array4, 2)
array4_round

array([[0.92, 0.36, 0.11, 0.26],
       [0.65, 0.04, 0.38, 0.72],
       [0.58, 0.75, 0.08, 0.09],
       [0.51, 0.65, 0.19, 0.04],
       [0.71, 0.3 , 0.71, 0.58],
       [0.62, 0.49, 0.06, 0.24]])

In [12]:
array4_round[:,1]

array([0.36, 0.04, 0.75, 0.65, 0.3 , 0.49])

In [13]:
#Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

array5 = np.random.randint(-50, 51, (30))
array5

array([ 16,  25,  12,  31,  49, -10, -45,  47,  10, -36, -29,  12,  31,
       -45,   7,   4,  18,  47,  48,  30,   4, -12, -33, -19, -43, -44,
        -6, -38,  33,  45])

In [14]:
resultado = array5[array5 < 0]
resultado 


array([-10, -45, -36, -29, -45, -12, -33, -19, -43, -44,  -6, -38])

In [15]:
mascara = array5 < 0

res = array5[mascara]
res

array([-10, -45, -36, -29, -45, -12, -33, -19, -43, -44,  -6, -38])

In [16]:
#Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

array6 = np.random.rand(10)
array6_round = np.round(array6, 2)
array6_round

array([0.74, 0.08, 0.48, 0.08, 0.95, 0.71, 0.19, 0.11, 0.39, 0.24])

In [17]:
np.where(array6_round > 0.5) #devulve las posiciones

(array([0, 4, 5], dtype=int64),)

In [18]:
#Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.


array7 = np.random.randint(1, 101, (40))
array7

array([ 49,  35,   7,  84,  66,   1, 100,  54,  87,  35,  95,  94,  38,
        85,   7, 100,  52,  97,  17,  94,  64,  88,  49,  52,   4,  84,
         7,   6,  64,   2,  92,  74,  45,  51,  56,  86,  17,  91,  14,
        34])

In [19]:
np.where((array7 % 3 == 0) & (array7 % 4 == 0))

(array([ 3, 25], dtype=int64),)

In [20]:
#BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [16]:
array_bonus = np.random.randint(1,101,(2, 3, 5))
array_bonus

array([[[ 63,  46,  98,  43,  22],
        [ 89,   3,  12,  76,   7],
        [ 33,  53,  33,  30,  73]],

       [[ 24,  69,  29,  39,  17],
        [ 43,   1,  13,  76,  47],
        [ 69,  45,  10,  46, 100]]])

In [19]:
def bonus(array):

    lista = np.reshape(array,(1,(array.size)))
    new_array = []
    forma = array.shape

    for e in lista[0]:
        if e %3 == 0:
            new_array.append(0)
        else:
            new_array.append(e)

    array_bonus_1 = np.array(new_array)
    array_final_bonus = np.reshape(array_bonus_1, forma)
    return array_final_bonus
    

In [21]:
solucion_bonus = bonus(array_bonus)
solucion_bonus

array([[[  0,  46,  98,  43,  22],
        [ 89,   0,   0,  76,   7],
        [  0,  53,   0,   0,  73]],

       [[  0,   0,  29,   0,  17],
        [ 43,   1,  13,  76,  47],
        [  0,   0,  10,  46, 100]]])

In [21]:
#Reshape y Transpose:
#Ejercicios con reshape:
#Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

array3D = np.random.randint(1, 101, (2, 3, 4))
array3D

array([[[100,  43,  54,  70],
        [ 96,  61,  48,  99],
        [ 46,  93,  16,  31]],

       [[ 77,  68,  86,  36],
        [ 70,   9,  99,  18],
        [ 12,  56,   7,  45]]])

In [22]:
np.reshape(array3D, (4,6), order = 'F')

array([[100,  46,  61,  54,  16,  99],
       [ 77,  12,   9,  86,   7,  18],
       [ 96,  43,  93,  48,  70,  31],
       [ 70,  68,  56,  99,  36,  45]])

In [23]:
np.reshape(array3D, (4,6), order = 'C')

array([[100,  43,  54,  70,  96,  61],
       [ 48,  99,  46,  93,  16,  31],
       [ 77,  68,  86,  36,  70,   9],
       [ 99,  18,  12,  56,   7,  45]])

In [24]:
# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

array3D2 = np.random.randint(1, 60, (3, 4, 5))
array3D2

array([[[ 9, 33, 39, 14, 58],
        [10, 47, 34, 49, 16],
        [27,  1, 32, 36, 42],
        [57, 12, 13, 13, 22]],

       [[24, 24, 32,  9, 56],
        [29, 55, 52, 56, 38],
        [44, 13, 19, 51, 59],
        [22,  6, 10,  6, 32]],

       [[13, 25,  9, 25,  8],
        [52, 34,  1,  4, 42],
        [49, 41, 28, 47, 10],
        [30, 41, 40,  2,  6]]])

In [25]:
np.reshape (array3D2, (10,6))

array([[ 9, 33, 39, 14, 58, 10],
       [47, 34, 49, 16, 27,  1],
       [32, 36, 42, 57, 12, 13],
       [13, 22, 24, 24, 32,  9],
       [56, 29, 55, 52, 56, 38],
       [44, 13, 19, 51, 59, 22],
       [ 6, 10,  6, 32, 13, 25],
       [ 9, 25,  8, 52, 34,  1],
       [ 4, 42, 49, 41, 28, 47],
       [10, 30, 41, 40,  2,  6]])

In [26]:
# Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.


array3D3 = np.random.rand(4, 3, 2)
array3D3

array([[[0.73985227, 0.10526854],
        [0.3988906 , 0.55050924],
        [0.88854739, 0.31450397]],

       [[0.94287539, 0.26349443],
        [0.40883826, 0.37239386],
        [0.30315691, 0.53038561]],

       [[0.20108491, 0.75035979],
        [0.41976795, 0.77203244],
        [0.97800106, 0.59837936]],

       [[0.16580341, 0.03099776],
        [0.9534611 , 0.48872474],
        [0.64203573, 0.02939245]]])

In [27]:
np.reshape (array3D3, (12,2))

array([[0.73985227, 0.10526854],
       [0.3988906 , 0.55050924],
       [0.88854739, 0.31450397],
       [0.94287539, 0.26349443],
       [0.40883826, 0.37239386],
       [0.30315691, 0.53038561],
       [0.20108491, 0.75035979],
       [0.41976795, 0.77203244],
       [0.97800106, 0.59837936],
       [0.16580341, 0.03099776],
       [0.9534611 , 0.48872474],
       [0.64203573, 0.02939245]])

In [28]:
# Ejercicios con transpose:
# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

array3D2 #array 3, 4, 5


array([[[ 9, 33, 39, 14, 58],
        [10, 47, 34, 49, 16],
        [27,  1, 32, 36, 42],
        [57, 12, 13, 13, 22]],

       [[24, 24, 32,  9, 56],
        [29, 55, 52, 56, 38],
        [44, 13, 19, 51, 59],
        [22,  6, 10,  6, 32]],

       [[13, 25,  9, 25,  8],
        [52, 34,  1,  4, 42],
        [49, 41, 28, 47, 10],
        [30, 41, 40,  2,  6]]])

In [29]:
np.transpose(array3D2)

array([[[ 9, 24, 13],
        [10, 29, 52],
        [27, 44, 49],
        [57, 22, 30]],

       [[33, 24, 25],
        [47, 55, 34],
        [ 1, 13, 41],
        [12,  6, 41]],

       [[39, 32,  9],
        [34, 52,  1],
        [32, 19, 28],
        [13, 10, 40]],

       [[14,  9, 25],
        [49, 56,  4],
        [36, 51, 47],
        [13,  6,  2]],

       [[58, 56,  8],
        [16, 38, 42],
        [42, 59, 10],
        [22, 32,  6]]])

In [30]:
# Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

array3D3 #4,3,2

array([[[0.73985227, 0.10526854],
        [0.3988906 , 0.55050924],
        [0.88854739, 0.31450397]],

       [[0.94287539, 0.26349443],
        [0.40883826, 0.37239386],
        [0.30315691, 0.53038561]],

       [[0.20108491, 0.75035979],
        [0.41976795, 0.77203244],
        [0.97800106, 0.59837936]],

       [[0.16580341, 0.03099776],
        [0.9534611 , 0.48872474],
        [0.64203573, 0.02939245]]])

In [31]:
np.transpose(array3D3, axes = (1, 2, 0))

array([[[0.73985227, 0.94287539, 0.20108491, 0.16580341],
        [0.10526854, 0.26349443, 0.75035979, 0.03099776]],

       [[0.3988906 , 0.40883826, 0.41976795, 0.9534611 ],
        [0.55050924, 0.37239386, 0.77203244, 0.48872474]],

       [[0.88854739, 0.30315691, 0.97800106, 0.64203573],
        [0.31450397, 0.53038561, 0.59837936, 0.02939245]]])

# Preguntas teóricas:
# ¿Qué diferencia existe entre el reshape y el transpose?

reshape cambia la forma del array manteniendo los mismos datos.
transpose intercambia filas y columnas en una matriz o un array multidimensional.

# ¿Y entre el transpose y el swapaxes?

transpose reorganiza todas las dimensiones de un array multidimensional, swapaxes solo intercambia dos ejes específicos 
sin cambiar el orden de las demás dimensiones.

In [32]:
# Funciones Aritméticas y Estadísticas:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

array_aritmetica_1 = np.round(np.random.rand(2, 3, 5),1)
array_aritmetica_1

array([[[0.6, 0.2, 1. , 0.6, 0.3],
        [0.6, 0.6, 0.8, 0.1, 1. ],
        [1. , 0.2, 0.7, 0.8, 0.4]],

       [[0.7, 0.3, 0.4, 0.3, 0. ],
        [0.4, 0.1, 0.2, 0.6, 0.6],
        [0.7, 0.6, 0.3, 0.9, 0.1]]])

In [33]:
# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 


array_aritmetica_2 = np.empty((2, 3, 5), dtype = float)
array_aritmetica_2

array([[[0.6, 0.2, 1. , 0.6, 0.3],
        [0.6, 0.6, 0.8, 0.1, 1. ],
        [1. , 0.2, 0.7, 0.8, 0.4]],

       [[0.7, 0.3, 0.4, 0.3, 0. ],
        [0.4, 0.1, 0.2, 0.6, 0.6],
        [0.7, 0.6, 0.3, 0.9, 0.1]]])

In [35]:
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las 
#siguientes condiciones: 
# Si el valor del array es igual que la media, se reemplaza por "A".
# Si el valor del array es mayor que la media, se reemplaza por "B".
# Si el valor del array es menor que la media, se reemplaza por "C".
# Si el valor es igual que el máximo, se reemplaza por "D".
# Si el valor es igual que el mínimo, se reemplaza por "E".


array_ultimo = np.empty((2, 3, 5), dtype = float)


In [36]:
array_ultimo

array([[[0.6, 0.2, 1. , 0.6, 0.3],
        [0.6, 0.6, 0.8, 0.1, 1. ],
        [1. , 0.2, 0.7, 0.8, 0.4]],

       [[0.7, 0.3, 0.4, 0.3, 0. ],
        [0.4, 0.1, 0.2, 0.6, 0.6],
        [0.7, 0.6, 0.3, 0.9, 0.1]]])

In [37]:
media = np.round(np.mean(array_aritmetica_2),1)
media

0.5

In [41]:
lista = list(np.reshape(array_ultimo, (30)))
lista[:2]

[0.6, 0.2]

In [49]:
def transformar_letras (array):
    lista_nueva = []
    forma = array.shape
    lista = list(np.reshape(array, (array.size)))

    for elemento in lista:
        if elemento == np.max(array):
            elemento = "D"
            lista_nueva.append(elemento)
        elif elemento == np.min(array):
            elemento = "E"
            lista_nueva.append(elemento)
        elif elemento == np.mean(array):
            elemento = "A"
            lista_nueva.append(elemento)
        elif elemento > np.mean(array):
            elemento = "B"
            lista_nueva.append(elemento)
        elif elemento < np.mean(array):
            elemento = "C"
            lista_nueva.append(elemento)
   
    array_final_1 = np.array(lista_nueva)
    array_final = np.reshape(array_final_1, forma)
    return array_final

In [50]:
array_sustiuido = transformar_letras(array_ultimo)

array_sustiuido

array([[['B', 'C', 'D', 'B', 'C'],
        ['B', 'B', 'B', 'C', 'D'],
        ['D', 'C', 'B', 'B', 'C']],

       [['B', 'C', 'C', 'C', 'E'],
        ['C', 'C', 'C', 'B', 'B'],
        ['B', 'B', 'C', 'B', 'C']]], dtype='<U1')

In [46]:
array_ultimo

array([[[0.6, 0.2, 1. , 0.6, 0.3],
        [0.6, 0.6, 0.8, 0.1, 1. ],
        [1. , 0.2, 0.7, 0.8, 0.4]],

       [[0.7, 0.3, 0.4, 0.3, 0. ],
        [0.4, 0.1, 0.2, 0.6, 0.6],
        [0.7, 0.6, 0.3, 0.9, 0.1]]])