In [2]:
import numpy as np
import random

In [7]:
#Creación y Indexación:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array = np.random.randint(10, 100, (50))
array

array([14, 94, 16, 83, 50, 96, 91, 52, 93, 72, 59, 71, 79, 73, 35, 10, 68,
       85, 86, 20, 39, 12, 42, 25, 56, 57, 56, 39, 64, 37, 79, 95, 60, 41,
       29, 75, 26, 16, 40, 75, 21, 44, 90, 81, 52, 29, 60, 76, 38, 41])

In [5]:
array[::5]

array([35, 33, 48, 86, 26, 20, 73, 42, 99, 42])

In [8]:
#Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

array1 = np.random.randint(1, 21, (30))
array1

array([15,  7,  3,  1, 12, 20, 20,  3,  5, 12,  7, 10,  9, 17,  3,  2, 16,
        9, 15, 20,  9,  3,  1, 14, 18, 13, 11,  5,  6,  1])

In [9]:
array1[::2]

array([15,  3, 12, 20,  5,  7,  9,  3, 16, 15,  9,  1, 18, 11,  6])

In [21]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
#Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array2D = np.random.rand(4, 6) * 30
array2D_round = np.round(array2D,2)
array2D_round

array([[ 2.28,  1.12,  5.83, 13.38,  5.1 ,  9.57],
       [ 9.46, 17.29,  9.93, 19.1 ,  9.86,  4.58],
       [21.46, 19.44, 28.28, 10.9 , 11.55, 16.9 ],
       [29.63, 16.6 , 15.79,  8.94, 27.67, 26.95]])

In [22]:
array2D_round[-1]

array([29.63, 16.6 , 15.79,  8.94, 27.67, 26.95])

In [24]:
#Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

array4 = np.random.rand(6, 4)
array4_round = np.round(array4, 2)
array4_round

array([[0.35, 0.37, 0.34, 0.15],
       [0.3 , 0.55, 0.11, 0.01],
       [0.5 , 0.12, 0.22, 0.92],
       [0.06, 0.49, 0.86, 0.94],
       [0.41, 0.86, 0.22, 0.59],
       [0.09, 0.31, 0.27, 0.69]])

In [25]:
array4_round[:,1]

array([0.37, 0.55, 0.12, 0.49, 0.86, 0.31])

In [26]:
#Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

array5 = np.random.randint(-50, 51, (30))
array5

array([ 17,  10,  24,  46,  29, -46, -45,  48,   3, -34,  -8,   9,  35,
       -23,  16, -39,   2,  -8,  46,  22,   6,  42,  35,  -3,  16,  32,
       -24,  43,  45,  21])

In [29]:
resultado = array5[array5 < 0]
resultado 


array([-46, -45, -34,  -8, -23, -39,  -8,  -3, -24])

In [31]:
mascara = array5 < 0

res = array5[mascara]
res

array([-46, -45, -34,  -8, -23, -39,  -8,  -3, -24])

In [34]:
#Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

array6 = np.random.rand(10)
array6_round = np.round(array6, 2)
array6_round

array([0.7 , 0.51, 0.93, 0.6 , 0.29, 0.18, 0.62, 0.65, 0.7 , 0.02])

In [35]:
np.where(array6_round > 0.5) #devulve las posiciones

(array([0, 1, 2, 3, 6, 7, 8], dtype=int64),)

In [36]:
#Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.


array7 = np.random.randint(1, 101, (40))
array7

array([ 1, 59, 36, 90, 65, 73, 70, 19, 39, 61, 13, 32, 68, 80, 64, 22, 62,
       27, 60, 65, 54, 37, 97, 65, 48, 89, 69, 26, 30, 76, 99, 95, 49, 38,
       17, 89, 83, 12, 67, 12])

In [38]:
np.where((array7 % 3 == 0) & (array7 % 4 == 0))

(array([ 2, 18, 24, 37, 39], dtype=int64),)

In [ ]:
#BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [39]:
#Reshape y Transpose:
#Ejercicios con reshape:
#Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

array3D = np.random.randint(1, 101, (2, 3, 4))
array3D

array([[[11, 12, 65, 88],
        [84, 23, 86, 98],
        [47, 49, 38, 70]],

       [[45,  4, 25, 57],
        [13, 13, 78, 22],
        [65, 93, 71, 88]]])

In [48]:
np.reshape(array3D, (4,6), order = 'F')

array([[11, 47, 23, 65, 38, 98],
       [45, 65, 13, 25, 71, 22],
       [84, 12, 49, 86, 88, 70],
       [13,  4, 93, 78, 57, 88]])

In [49]:
np.reshape(array3D, (4,6), order = 'C')

array([[11, 12, 65, 88, 84, 23],
       [86, 98, 47, 49, 38, 70],
       [45,  4, 25, 57, 13, 13],
       [78, 22, 65, 93, 71, 88]])

In [50]:
# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

array3D2 = np.random.randint(1, 60, (3, 4, 5))
array3D2

array([[[18, 46, 33, 54, 36],
        [14,  9, 21, 35, 51],
        [39,  2,  5, 26, 48],
        [53, 16, 49, 19, 18]],

       [[ 6, 18, 42, 52, 20],
        [22,  3, 22, 19, 52],
        [ 8,  7, 29, 55,  7],
        [13, 41,  4, 37, 57]],

       [[37, 31, 27,  7, 14],
        [35, 13, 37, 23, 33],
        [ 5, 54, 47, 39, 21],
        [16, 58, 12,  1, 57]]])

In [52]:
np.reshape (array3D2, (10,6))

array([[18, 46, 33, 54, 36, 14],
       [ 9, 21, 35, 51, 39,  2],
       [ 5, 26, 48, 53, 16, 49],
       [19, 18,  6, 18, 42, 52],
       [20, 22,  3, 22, 19, 52],
       [ 8,  7, 29, 55,  7, 13],
       [41,  4, 37, 57, 37, 31],
       [27,  7, 14, 35, 13, 37],
       [23, 33,  5, 54, 47, 39],
       [21, 16, 58, 12,  1, 57]])

In [53]:
# Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.


array3D3 = np.random.rand(4, 3, 2)
array3D3

array([[[0.36696212, 0.95421488],
        [0.15769215, 0.91249844],
        [0.95928043, 0.52539793]],

       [[0.91227143, 0.41763897],
        [0.5819852 , 0.1578055 ],
        [0.69900025, 0.18813771]],

       [[0.66310922, 0.48940126],
        [0.31213911, 0.75449541],
        [0.98412635, 0.12387946]],

       [[0.56556981, 0.81661706],
        [0.28811228, 0.09296745],
        [0.76766088, 0.724971  ]]])

In [54]:
np.reshape (array3D3, (12,2))

array([[0.36696212, 0.95421488],
       [0.15769215, 0.91249844],
       [0.95928043, 0.52539793],
       [0.91227143, 0.41763897],
       [0.5819852 , 0.1578055 ],
       [0.69900025, 0.18813771],
       [0.66310922, 0.48940126],
       [0.31213911, 0.75449541],
       [0.98412635, 0.12387946],
       [0.56556981, 0.81661706],
       [0.28811228, 0.09296745],
       [0.76766088, 0.724971  ]])

In [55]:
# Ejercicios con transpose:
# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

array3D2 #array 3, 4, 5


array([[[18, 46, 33, 54, 36],
        [14,  9, 21, 35, 51],
        [39,  2,  5, 26, 48],
        [53, 16, 49, 19, 18]],

       [[ 6, 18, 42, 52, 20],
        [22,  3, 22, 19, 52],
        [ 8,  7, 29, 55,  7],
        [13, 41,  4, 37, 57]],

       [[37, 31, 27,  7, 14],
        [35, 13, 37, 23, 33],
        [ 5, 54, 47, 39, 21],
        [16, 58, 12,  1, 57]]])

In [58]:
np.transpose(array3D2)

array([[[18,  6, 37],
        [14, 22, 35],
        [39,  8,  5],
        [53, 13, 16]],

       [[46, 18, 31],
        [ 9,  3, 13],
        [ 2,  7, 54],
        [16, 41, 58]],

       [[33, 42, 27],
        [21, 22, 37],
        [ 5, 29, 47],
        [49,  4, 12]],

       [[54, 52,  7],
        [35, 19, 23],
        [26, 55, 39],
        [19, 37,  1]],

       [[36, 20, 14],
        [51, 52, 33],
        [48,  7, 21],
        [18, 57, 57]]])

In [59]:
# Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

array3D3 #4,3,2

array([[[0.36696212, 0.95421488],
        [0.15769215, 0.91249844],
        [0.95928043, 0.52539793]],

       [[0.91227143, 0.41763897],
        [0.5819852 , 0.1578055 ],
        [0.69900025, 0.18813771]],

       [[0.66310922, 0.48940126],
        [0.31213911, 0.75449541],
        [0.98412635, 0.12387946]],

       [[0.56556981, 0.81661706],
        [0.28811228, 0.09296745],
        [0.76766088, 0.724971  ]]])

In [64]:
np.transpose(array3D3, axes = (1, 2, 0))

array([[[0.36696212, 0.91227143, 0.66310922, 0.56556981],
        [0.95421488, 0.41763897, 0.48940126, 0.81661706]],

       [[0.15769215, 0.5819852 , 0.31213911, 0.28811228],
        [0.91249844, 0.1578055 , 0.75449541, 0.09296745]],

       [[0.95928043, 0.69900025, 0.98412635, 0.76766088],
        [0.52539793, 0.18813771, 0.12387946, 0.724971  ]]])

# Preguntas teóricas:
# ¿Qué diferencia existe entre el reshape y el transpose?

reshape cambia la forma del array manteniendo los mismos datos.
transpose intercambia filas y columnas en una matriz o un array multidimensional.

# ¿Y entre el transpose y el swapaxes?

transpose reorganiza todas las dimensiones de un array multidimensional, swapaxes solo intercambia dos ejes específicos 
sin cambiar el orden de las demás dimensiones.

In [66]:
# Funciones Aritméticas y Estadísticas:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

array_aritmetica_1 = np.round(np.random.rand(2, 3, 5),1)
array_aritmetica_1

array([[[0.7, 0.6, 0.1, 0.5, 0.6],
        [0.3, 0.3, 0.5, 0.4, 0.1],
        [0.9, 0.6, 0.1, 0.5, 0.6]],

       [[0.4, 0.3, 0.9, 0.6, 0.1],
        [0.4, 0. , 0.3, 0.3, 1. ],
        [0.3, 0.7, 0.3, 0.2, 0.7]]])

In [68]:
# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 


array_aritmetica_2 = np.empty((2, 3, 5), dtype = float)
array_aritmetica_2

array([[[0.7, 0.6, 0.1, 0.5, 0.6],
        [0.3, 0.3, 0.5, 0.4, 0.1],
        [0.9, 0.6, 0.1, 0.5, 0.6]],

       [[0.4, 0.3, 0.9, 0.6, 0.1],
        [0.4, 0. , 0.3, 0.3, 1. ],
        [0.3, 0.7, 0.3, 0.2, 0.7]]])

In [72]:
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
# Si el valor del array es igual que la media, se reemplaza por "A".
media = np.round(np.mean(array_aritmetica_2),1)
media

0.4

In [74]:
array_media_A = np.where(array_aritmetica_2 == np.mean(array_aritmetica_2), 'A', 'No')
array_media_A

array([[['No', 'No', 'No', 'No', 'No'],
        ['No', 'No', 'No', 'No', 'No'],
        ['No', 'No', 'No', 'No', 'No']],

       [['No', 'No', 'No', 'No', 'No'],
        ['No', 'No', 'No', 'No', 'No'],
        ['No', 'No', 'No', 'No', 'No']]], dtype='<U2')

In [ ]:
# Si el valor del array es mayor que la media, se reemplaza por "B".



In [ ]:
# Si el valor del array es menor que la media, se reemplaza por "C".



In [ ]:
# Si el valor es igual que el máximo, se reemplaza por "D".


In [ ]:

# Si el valor es igual que el mínimo, se reemplaza por "E".