# PANDAS

In [1]:
import pandas as pd
import numpy as np
import random

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

-Serie  
    unidimensional
    datos homogeneos

- DATAFRAME
    bidimensional
    Datos diferentes 

2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

Extrae el valor para el índice "lunes"

Extrae el valor para el índice "lunes", "martes" y "miércoles".

Extrae el valor para el índice "lunes" y "domingo".

In [15]:
# Crea dos listas:

array = np.random.randint(0,7,(7))
print(type(array))
print(array)
valores = list(array)
print(type(valores))


indices = ["L","M","X","J","V","S","D"]


<class 'numpy.ndarray'>
[0 3 1 1 4 6 6]
<class 'list'>


In [17]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.
pd.Series(valores,index=indices)

L    0
M    3
X    1
J    1
V    4
S    6
D    6
dtype: int32

In [25]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.
dict_semana= dict(zip(indices,valores))
dict_semana


{'L': 0, 'M': 3, 'X': 1, 'J': 1, 'V': 4, 'S': 6, 'D': 6}

In [26]:
#Crea una Serie con el diccionario creado en el punto anterior.
pd.Series(dict_semana)

L    0
M    3
X    1
J    1
V    4
S    6
D    6
dtype: int32

In [28]:
# Que forma

serie_semana= pd.Series(dict_semana)
print(serie_semana.shape)
print(serie_semana.size)
print(serie_semana.dtype)

(7,)
7
int32


In [29]:
#¿Cuáles son los índices de la Serie?
print(f"Valores {serie_semana.values}")

#¿Y los values?
print(f"Indices {serie_semana.index}")

Valores [0 3 1 1 4 6 6]
Indices Index(['L', 'M', 'X', 'J', 'V', 'S', 'D'], dtype='object')


In [48]:
#Extrae el valor para el índice "lunes"
print(serie_semana["L"])


#Extrae el valor para el índice "lunes", "martes" y "miércoles".
print("_____________")
print(serie_semana[0:3])
print(serie_semana.values[0:3])

#Extrae el valor para el índice "lunes" y "domingo".
print("_____________")
print(serie_semana[::6])
print(serie_semana.values[::6])


0
_____________
L    0
M    3
X    1
dtype: int32
[0 3 1]
_____________
L    0
D    6
dtype: int32
[0 6]


3. Es el turno de los DataFrames

Crea un array de dos dimensiones con 4 filas y 3 columnas.

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

Descarga el archivo "medallas" y carga el DataFrame.

Usando el loc extrae todas las columnas de la fila de Tailandia.

Usando el loc extrae todas las columnas de China e Irán.

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

Usando el iloc extrae la información de la India. Devolved todas las columnas.

Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [49]:
#Crea un array de dos dimensiones con 4 filas y 3 columnas.
array_ej3 = np.random.randint(0,100,(4,3))
array_ej3

array([[92, 72, 18],
       [52, 11, 58],
       [58, 42, 69],
       [21, 53, 13]])

In [56]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
encabezados = ["España","Francia","Italia"]
df_paises = pd.DataFrame(array_ej3, columns=encabezados)
df_paises

España  Francia  Italia
0      92       72      18
1      52       11      58
2      58       42      69
3      21       53      13

In [60]:
#Descarga el archivo "medallas" y carga el DataFrame.

df_medallas= pd.read_csv("files/medallas.csv", index_col=0)
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [63]:
#Usando el loc extrae todas las columnas de la fila de Tailandia

filas_tailandia = df_medallas.loc[df_medallas["País"]=="Tailandia" ,:]
filas_tailandia

País  Oro  Plata  Bronce
7  Tailandia  132    175     278

In [65]:
#Usando el loc extrae todas las columnas de China e Irán.
filas_c_i = df_medallas.loc[(df_medallas["País"]=="China") | (df_medallas["País"]=="Irán"), :]
filas_c_i

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [92]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
medallas_c_e = df_medallas.loc[(df_medallas["País"]=="China") | (df_medallas["País"]=="Irán"),"Oro"::]
medallas_c_e

Oro  Plata  Bronce  Total_medallas
1  1473    994     720            3187
4   179    181     197             557

In [93]:
# En el loc, pasamos el indice de la lista de columnas
df_medallas.columns[1::]

Index(['Oro', 'Plata', 'Bronce', 'Total_medallas'], dtype='object')

In [94]:
medallas_c_e = df_medallas.loc[(df_medallas["País"]=="China") | (df_medallas["País"]=="Irán"),df_medallas.columns[1::]]
medallas_c_e

Oro  Plata  Bronce  Total_medallas
1  1473    994     720            3187
4   179    181     197             557

In [74]:
#Usando el iloc extrae la información de la India. Devolved todas las columnas.
info_india = df_medallas.iloc[5,:]
info_india

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [79]:
#Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
paises_posicion_par = df_medallas.iloc[1::2,:]
paises_posicion_par

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [80]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
paises_posicion_par_medalla = df_medallas.iloc[1::2,1:]
paises_posicion_par_medalla

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [88]:
#Contesta a las siguientes preguntas:

#¿Qué país consiguió más de 200 medallas de oro?

paises_medallas_oro = df_medallas.loc[df_medallas["Oro"]>200, "País"]
print(f"Paises con medalla de oro:\n{paises_medallas_oro}")
print("_____________")
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
paises_medallas_oro_plata = df_medallas.loc[(df_medallas["Oro"]>200) & (df_medallas["Plata"]>1000), "País"]
print(f"Paises con medalla de oro y plata:\n{paises_medallas_oro_plata}")
print("_____________")

#¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
paises_medallas_oro_bronce= df_medallas.loc[(df_medallas["Oro"]>200) | (df_medallas["Bronce"]>700), "País"]
print(f"Paises con medalla de oro y bronce:\n{paises_medallas_oro_bronce}")


Paises con medalla de oro:
1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object
_____________
Paises con medalla de oro y plata:
2    Japón
Name: País, dtype: object
_____________
Paises con medalla de oro y bronce:
1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object


In [89]:
#Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas["Total_medallas"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]
df_medallas

País   Oro  Plata  Bronce  Total_medallas
1             China  1473    994     720            3187
2             Japón  1032   1037     985            3054
3     Corea del Sur   745    663     827            2235
4              Irán   179    181     197             557
5        Kazajistán   155    158     224             537
6             India   154    202     315             671
7         Tailandia   132    175     278             585
8         Indonesia   112    131     240             483
9      China Taipéi    99    144     276             519
10  Corea del Norte    91    120     235             446